future: true
permalink: /:title/
url: http://Binly42.github.io
name: Binly42
author: Binly42
qq: ******
email: ******

duoshuo: yourname
beian:
cnzz:
weibo:
github: Binly42
about: "这里是 Binly42 的个人博客, 创建于 20180315, 博客模板沿用 pmlpml 老师的 jekyll 模板"

safe: true
paginate: 20
